Update stor script to handle status options Update Client log

diff --git a/bin/stor b/bin/stor
--- a/bin/stor
+++ b/bin/stor
@@ -16,6 +16,7 @@ OPTIONS:
     -c      Start the client
     -s      Start the server 
     -k      Kill the Stor server
+    -x      Get the status of the Stor server
 
 SERVER OPTIONS:
     -p      The host address to be used by the Pastry server. This is required
@@ -48,7 +49,7 @@ HOST_ADDR=
 FILENAME=
 FILEID=
 ACTION=
-while getopts "p:f:a:i:schk" opt; do
+while getopts "p:f:a:i:schkx" opt; do
   case $opt in
     h)
         usage
@@ -75,6 +76,9 @@ while getopts "p:f:a:i:schk" opt; do
     k)
         killserver
         exit 0
+      ;;
+    x)
+        CMD=Status
       ;;
     ?)
         usage
@@ -130,7 +134,7 @@ if [ "$CMD" = "Client" ]; then
         exit 1
     fi	
 
-else
+elif [ "$CMD" = "Server" ]; then
     if [[ -z $HOST_ADDR ]]; then 
         echo "Missing required host address parameter"
         usage
@@ -138,4 +142,12 @@ else
     fi
     echo "starting server using host address: $HOST_ADDR!" >&2
     $JAVA_HOME/bin/java -classpath $STOR/lib/stor-1.0.jar com.stor.server.Server $HOST_ADDR &
+
+elif [ "$CMD" = "Status" ]; then
+    $JAVA_HOME/bin/java -classpath $STOR/lib/stor-1.0.jar com.stor.client.Client STATUS
+
+else
+    echo "Invalid Command: $CMD"
+    usage
+    exit 1
 fi
